/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4/userguide/building_java_projects.html
 */

plugins {
    // TODO - switch to library.
    // Apply the java-library plugin for API and implementation separation.
    //`java-library`
    application
}

// APPLICATION BITS
application {
    mainClass.set("jugglingLab.JugglingLab")
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "jugglinglab.JugglingLab"
    }
}

// END APPLICATION BITS

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

sourceSets {
    main {
        java {
            setSrcDirs(listOf("src/jugglinglab", "src/alternatives"))
        }
    }
}

dependencies {
    // Should this be api? api doesn't exist for an application.
    implementation("org.apache.commons:commons-math3:3.6.1")
    implementation("com.google.ortools:ortools-java:9.2.9972")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    // implementation("com.google.guava:guava:30.1.1-jre")
}

// TODO - why doesn't this work?
// defaultTasks("upper")

tasks.register("upper") {
    doLast {
        val someString = "mY_nAmE"
        println("Original: $someString")
        println("Upper case: ${someString.toUpperCase()}")
    }
}

tasks.register("dev") {
    dependsOn("jar")
}

version = "1.6.2"